name: explore_tainan_web
description: "「一府 x iF」遊城活動打卡"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_line_liff: ^1.0.0+1
  flutter_native_splash: ^2.4.5
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# flutter_native_splash: 
#   color: "#f1efe9"
#   image: assets/animations/travelerAnimation.gif

flutter:
  fonts:
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC.ttf
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    
  
