name: explore_tainan_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.1
  custom_info_window: ^1.0.1
  fconsole: ^2.6.2
  fimber: ^0.7.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_line_liff: ^0.1.0
  google_maps_flutter: ^2.10.0
  google_maps_flutter_platform_interface: ^2.9.5
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.3.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
  
